### ISSUE TITLE
Suitable for 3 phase?

### ISSUE THREAD

**Issue by eina84** [JGAguado/Smart_Powermeter#11]
I just purchased one of your units on Elecrow today to replace my Neurio unit which is no longer supported & appears to have stopped working.
Is the Smart Powermeter suitable for 3 phase? My condo uses 3 phase.
Also, I ordered the pack with 6 CT Clamps - can I use 3 of them to measure the 3 phase input & then the other 3 to maybe measure specific current draws of 3 big items like my air conditioners?
(sorry if this isn't the right place to ask - I couldn't find another site with discussion area)

**Comment by JGAguado** [comment]
Dear @eina84,

Yes, my apartment also uses triphasic. I am monitoring each one of the phases and so far works fine for me, and yes, with the other 3 clamps you should have no problems monitoring other current lines. 
By monitoring each of the phases I compute on ESPHome the total apparent power this way:

``` 
 - platform: template
    id: current_power
    name: "Measured Power"
    lambda: return (id(Probe_1).state + id(Probe_2).state + id(Probe_3).state) * 230.0 / 1000; #Apparent power = Current * Voltage 
    unit_of_measurement: 'kW'
    update_interval: 5s
```

This is a pic of the first version of the Smart Powermeter, but the concept is the same:
![image](https://github.com/JGAguado/Smart_Powermeter/assets/7847822/eb77369d-013c-4634-a827-de43e0a5c62f)

I will close this issue now, but for further questions don't hesitate to write me by email ([jon.garcia.aguado@gmail.com](mailto:jon.garcia.aguado@gmail.com)) or IG ([@JGAguado](https://www.instagram.com/JGaguado/)), I may answer faster.

Best regards and thanks for the support!

Jon
