### ISSUE TITLE
ESP-IDF attenuation 11db changed to 12db

### ISSUE THREAD

**Issue by n2kbg** [JGAguado/Smart_Powermeter#27]
For the esphome configuration.yaml ESPHome now warns that:

  `WARNING "attenuation: 11db" is deprecated, use "attenuation: 12db" instead`

See[ esphome 2024.5.0 release notes](https://esphome.io/changelog/2024.5.0.html) for details.

**Comment by JGAguado** [comment]
Thanks for the heads-up! Fixed on commit c1eb5d78a81a99daf929d4152a6007f1a533bf61
