### ISSUE TITLE
ESPHome syntax updates with 2024.6.x

### ISSUE THREAD

**Issue by n2kbg** [JGAguado/Smart_Powermeter#31]
ESPHome 2024.06 introduced a major breaking change in the syntax for the 'ota:' section of the yaml config. It now needs to look like this:

```
ota:
  platform: esphome
```

https://esphome.io/changelog/2024.6.0.html#ota-platforms

**Comment by n2kbg** [comment]
Simple enough change so here is a pull request

#32

**Comment by JGAguado** [comment]
Thanks for the PR @n2kbg  😃 !
