### ISSUE TITLE
Not 0 when mo power  !

### ISSUE THREAD

**Issue by vincegre** [JGAguado/Smart_Powermeter#36]
Hi

Just bought the complete kit and I'm quite impressed by quality of the board and design but I have an annoying issue. Even without CT connected or CT connected but laying on table, ESPHome reports some small consumptions on each input ! I have around 100W measured while it should be 0.
I'm using your default code as you supply. How to fix the problem ?

Thanks

Vincèn

**Comment by JGAguado** [comment]
Hi Vincèn,

Thanks for supporting the project! It can be that you may need to play around the calibration coefficients associated to each CT clamp. @lucazeta1975 opened some days ago a nice [discussion ](https://github.com/JGAguado/Smart_Powermeter/discussions/35) with some updated calibration factors, I'd recommend them to give them a try or check out the [calibration procedure from the docs ](https://smart-powermeter.readthedocs.io/en/v2r2/installation.html#calibration) 😉😉.

Let me know if this helps.

PS: I'm converting this issue to a discussion as it fits better.
